import { QueueItem, VFXModuleState, CharacterRef, BrollState, AIMVState, SemanticChip } from '../types';
import { MODULE_DISPLAY_NAMES } from '../constants';
const chipText=(chips:SemanticChip[])=>chips.map(c=>c.family?`${c.family}: ${c.value}`:c.value).join(', ');
export function compileVFXPrompt(item: QueueItem, modules: VFXModuleState[], chars: CharacterRef[], context: string){
 const modText = modules.map(m=>`[${MODULE_DISPLAY_NAMES[m.id]}] ${m.directive || chipText(m.chips) || 'module enabled'}${m.renderText?` Render exact text: "${m.renderText}".`:''}${m.activeConcept?.sourceTimecode?` Peak visual reference hits at ${m.activeConcept.sourceTimecode}.`:''}`).join('\n');
 return `MASTER VIDEO GENERATION & COMPOSITING DIRECTIVE:\nUse the provided base source clip as the foundation. Preserve original subject identity, timing, camera movement, lighting direction, framing, color grade, wardrobe, lip sync, and spatial composition exactly. Only add the selected SHOTFX modules.\n\nPROJECT CONTEXT:\n${context || item.context || 'High-end cinematic rap music video VFX pass.'}\n\nACTIVE MODULES:\n${modText || 'No modules enabled.'}\n\nCHARACTER LOCK:\n${chars.length?chars.map(c=>`Subject ${c.subject}: ${c.name}`).join('\n'):'No external character replacement; preserve source subjects.'}\n\nTEMPORAL STABILITY:\nFrame-to-frame stability is mandatory. Track camera motion, match parallax, occlusion, lighting, shadows, depth, and motion blur. Generated references are midpoint/peak-state targets.\n\nSYSTEM INSTRUCTION: DO NOT render prompt text, brackets, metadata, UI labels, captions, or technical instructions on screen.`;
}
export function compileBrollPrompt(b:BrollState, context:string){ return `Generate adjacent cinematic B-roll coverage. This is not a 1:1 VFX edit. Create a new ${b.shotType} shot that matches the lighting, color grade, lens feeling, contrast, environment texture, and music-video mood of the provided Reference DNA. Avoid people unless Character Lock is active. Style Directive: ${chipText(b.styleTerms)}. Context: ${context||'high-end gritty rap music video coverage'}.`; }
export function compileAIMVPrompt(mv:AIMVState, context:string){ return `AI MV motion transfer prompt. Anti-Fake Mode: ${mv.antiFake?'ON - photoreal, real camera, real place, realistic skin and editorial rapper portrait':'OFF - style hyperlinks may control render style'}. Motion source: ${mv.motionSource}. Character Lock controls identity. Performance clip controls lip sync, mouth movement, head/body/hand timing, rhythm, and energy. World Ref controls environment and lighting. Scene Ref controls composition when used. Context: ${context||'modern music video performance'}.`; }
export function optimizePrompt(prompt:string){ return prompt.replace(/\n{3,}/g,'\n\n').replace(/\s{2,}/g,' ').trim(); }
export function animatePlan(kind:string, tc?:string){ const peak=tc || 'the selected playhead midpoint'; return `\n\nVFX ANIMATION PLAN:\nENTRY: The ${kind} builds into the scene before ${peak}, motivated by source camera movement and subject gesture.\nPEAK / MIDPOINT: The effect matches the generated reference exactly at ${peak}.\nHOLD / INTEGRATION: It remains camera-tracked with correct parallax, occlusion, shadows, reflected light, and motion blur.\nEXIT: The effect exits with material-appropriate motion, dissipating without jitter or text labels.\nTRACKING / COMPOSITING: Treat the effect as a real photographed object/effect inside the plate, not a flat overlay.`; }
