import { useState } from 'react';
import { Button, Icon, SectionLabel } from './UIPrimitives';
const MANIFEST=`SHOTFX RACK MASTER MANIFEST\n\nSHOTFX Rack is a dark cinematic modular AI/VFX production cockpit for music videos. It has a left media viewport, bottom timeline, right control rack, VFX Rack, B-Roll, AI MV, Character Lock, Discovery Window, Prompt Densifier, Design Hero, and Final Command Center.\n\nCore rule: VFX Rack preserves uploaded source footage and augments it. B-Roll creates adjacent cinematic coverage from Reference DNA. AI MV creates photoreal anti-fake world/scene refs and motion transfer prompts.\n\nVisual style: #050505 black canvas, charcoal panels, white active tabs, electric blue accents, rounded cards, uppercase tracked labels, monospace prompt editors, blue semantic chips.\n\nDo not redesign unrelated systems. Do not show prompt text over media. Do not make B-Roll generate people unless Character Lock is active. Do not make VFX restage footage. Final Export must use the edited prompt.`;
export function SettingsModal({onClose}:{onClose:()=>void}){ const [copied,setCopied]=useState(false); const copy=async()=>{await navigator.clipboard.writeText(MANIFEST); setCopied(true); setTimeout(()=>setCopied(false),1500)}; const dl=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([MANIFEST],{type:'text/plain'}));a.download='shotfx-master-manifest.txt';a.click();}; const runtimeGuide=`To enable real AI generation, set these server-side values in Vercel (not in browser code):
- GOOGLE_API_KEY: your Google AI API key
- GOOGLE_IMAGE_MODEL: default image model (optional)
- GOOGLE_VIDEO_MODEL: default video model (optional)
- GOOGLE_IMAGE_API_URL / GOOGLE_VIDEO_API_URL: optional custom provider endpoints
The app now sends prompts to /api/generate-image and /api/generate-video, so production keys stay on the server.`; return <div className="modal-back high"><div className="settings"><header><SectionLabel icon="settings">System Settings</SectionLabel><button className="x" onClick={onClose}><Icon name="close"/></button></header><section><SectionLabel icon="description">Tool Source / Manifest</SectionLabel><div className="two"><Button onClick={copy}><Icon name="content_copy"/> {copied?'Copied':'Copy Manifest'}</Button><Button onClick={dl}><Icon name="download"/> Manifest.txt</Button></div></section><section><SectionLabel icon="code">Runtime API Setup</SectionLabel><div className="disabled-box"><Icon name="cloud" size={34}/><p style={{whiteSpace:'pre-line'}}>{runtimeGuide}</p></div></section><section><SectionLabel icon="code">Source Bundle</SectionLabel><div className="disabled-box"><Icon name="folder_off" size={34}/><p>This standalone rebuild includes source files in the zip. The original Flow runtime source export was unavailable.</p></div></section></div></div> }
