import { useState } from 'react';
import { IMAGE_PROVIDERS, VIDEO_PROVIDERS } from '../constants';
import { RuntimeProviderConfig } from '../types';
import { Button, Field, Icon, SectionLabel, Select } from './UIPrimitives';

const MANIFEST=`SHOTFX RACK MASTER MANIFEST\n\nSHOTFX Rack is a dark cinematic modular AI/VFX production cockpit for music videos. It has a left media viewport, bottom timeline, right control rack, VFX Rack, B-Roll, AI MV, Character Lock, Discovery Window, Prompt Densifier, Design Hero, and Final Command Center.\n\nCore rule: VFX Rack preserves uploaded source footage and augments it. B-Roll creates adjacent cinematic coverage from Reference DNA. AI MV creates photoreal anti-fake world/scene refs and motion transfer prompts.\n\nVisual style: #050505 black canvas, charcoal panels, white active tabs, electric blue accents, rounded cards, uppercase tracked labels, monospace prompt editors, blue semantic chips.\n\nDo not redesign unrelated systems. Do not show prompt text over media. Do not make B-Roll generate people unless Character Lock is active. Do not make VFX restage footage. Final Export must use the edited prompt.`;

interface SettingsModalProps {
  onClose: () => void;
  config: RuntimeProviderConfig;
  onChange: (patch: Partial<RuntimeProviderConfig>) => void;
}

export function SettingsModal({ onClose, config, onChange }: SettingsModalProps){
  const [copied,setCopied]=useState(false);
  const copy=async()=>{await navigator.clipboard.writeText(MANIFEST); setCopied(true); setTimeout(()=>setCopied(false),1500)};
  const dl=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([MANIFEST],{type:'text/plain'}));a.download='shotfx-master-manifest.txt';a.click();};

  return <div className="modal-back high"><div className="settings"><header><SectionLabel icon="settings">System Settings</SectionLabel><button className="x" onClick={onClose}><Icon name="close"/></button></header><section><SectionLabel icon="description">Tool Source / Manifest</SectionLabel><div className="two"><Button onClick={copy}><Icon name="content_copy"/> {copied?'Copied':'Copy Manifest'}</Button><Button onClick={dl}><Icon name="download"/> Manifest.txt</Button></div></section><section><SectionLabel icon="bolt">Provider Runtime</SectionLabel><div className="disabled-box"><p>Use API-key driven provider routing. Keys are sent to the server on each generation request, so they never need to live in browser bundle code.</p></div><Select label="Image Provider" value={config.imageProvider} options={IMAGE_PROVIDERS} onChange={value=>onChange({imageProvider:value})}/><Field label="Image API Key" value={config.imageApiKey} placeholder="Paste image provider key" onChange={value=>onChange({imageApiKey:value})}/><Field label="Image Endpoint (optional)" value={config.imageEndpoint} placeholder="Override endpoint URL" onChange={value=>onChange({imageEndpoint:value})}/><Field label="Custom Image Model" value={config.customImageModel} placeholder="Use when you need a custom model name" onChange={value=>onChange({customImageModel:value})}/><Select label="Video Provider" value={config.videoProvider} options={VIDEO_PROVIDERS} onChange={value=>onChange({videoProvider:value})}/><Field label="Video API Key" value={config.videoApiKey} placeholder="Paste video provider key" onChange={value=>onChange({videoApiKey:value})}/><Field label="Video Endpoint (optional)" value={config.videoEndpoint} placeholder="Override endpoint URL" onChange={value=>onChange({videoEndpoint:value})}/><Field label="Custom Video Model" value={config.customVideoModel} placeholder="Use when you need a custom model name" onChange={value=>onChange({customVideoModel:value})}/></section><section><SectionLabel icon="code">Source Bundle</SectionLabel><div className="disabled-box"><Icon name="folder_off" size={34}/><p>This standalone rebuild includes source files in the zip. The original Flow runtime source export was unavailable.</p></div></section></div></div> }
